# Typed subset of Ansible's callback API used by the timing observer.

from typing import Protocol

class CallbackDisplay(Protocol):
    # Ansible's plain-text callback output sink.

    def display(self, msg: str) -> None: ...

class CallbackBase:
    # Upstream callback hooks; event payloads require explicit narrowing.

    _display: CallbackDisplay

    def __init__(self) -> None: ...
    def v2_playbook_on_start(self, playbook: object) -> None: ...
    def v2_runner_on_start(self, host: object, task: object) -> None: ...
    def v2_runner_on_ok(self, result: object) -> None: ...
    def v2_runner_on_failed(self, result: object, ignore_errors: bool = False) -> None: ...
    def v2_runner_on_skipped(self, result: object) -> None: ...
    def v2_runner_on_unreachable(self, result: object) -> None: ...
    def v2_playbook_on_stats(self, stats: object) -> None: ...
